version: '3.1'

services:

  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    networks:
      default:
        external:
          name: kafka-net
    depends_on:
      - zookeeper_kafkanet
    links:
      - zookeeper_kafkanet
    restart: always
    ports:
      - 6627:6627

  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    networks:
      default:
        external:
          name: kafka-net
    depends_on:
      - nimbus
      - zookeeper_kafkanet
    links:
      - nimbus
      - zookeeper_kafkanet
    restart: always